# Requirements

The proposed project is basically labor-intensive. It requires time input
in several aspects:
 - Building translation tooling, i.e., `potools`
 - Designing the useR! workshop
 - Reviewing existing translations
 - Researching translation best practices
 - Soliciting and vetting new and/or updated translations
 - Translation itself
 
The first two of these would basically be done by me.
Review and research could be done with additional headcount
Work involving R translations ultimately needs an R Core member with commit rights;
solicitation could be done on r-project.org and/or through word-of-mouth.
Translation of course requires native speakers also very comfortable with English.

## People
<!--
Who needs to be involved, what's the proposed structure, what will it take to get their involvement?
-->

## Processes
<!-- 
What processes need to be put in place e.g. codes of conduct, regular ISC meetings, handover to the community at large?
-->

## Tools & Tech

`potools` will be the primary tool for this project.
<!--
What is going to be needed to deliver this project? 

Will cloud computing be used - if yes are there are necessary components that will be deciding factors between providers?

Are there tools or tech that don't exist that will be produced to facilitate the project?
-->

## Funding
<!-- 
[TO DO] THE GUIDANCE IS PRETTY UNCLEAR, ESP IN LIGHT OF GABOR'S PROPOSAL VS AWARD SIZE

-->

## Summary
<!--
A summary of the requirements that contextualises the costs
-->